name: TV_Subscribe

on:
  workflow_dispatch:
jobs:
  build:
    name: TV_Subscribe
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.x"